#include <unistd.h>
#include <limits.h>
#include <stdio.h>
#include <string.h>
#include <errno.h>

#define	LIMIT_COMPILE_TIME	0
#define	LIMIT_RUNTIME_SYS	1
#define	LIMIT_RUNTIME_PATH	2

typedef struct limit {
	char *name;
	long long value;
	char *desc;
} limit_t;

//ISO C compile-time Limits, size of integral values
limit_t lim_isoc[] = {
	{"CHAR_BIT", 	CHAR_BIT, 	"bits in a char"},
	{"CHAR_MAX", 	CHAR_MAX, 	"max value of char"},	
	{"CHAR_MIN", 	CHAR_MIN, 	"min value of char"},	
	{"SCHAR_MAX", 	SCHAR_MAX, 	"max value of signed char"},	
	{"SCHAR_MIN", 	SCHAR_MIN, 	"min value of signed char"},	
	{"UCHAR_MAX", 	UCHAR_MAX, 	"max value of unsigned char"},
	{"INT_MAX", 	INT_MAX, 	"max value of int"},
	{"INT_MIN", 	INT_MIN, 	"min value of int"},
	{"UINT_MAX", 	UINT_MAX, 	"max value of unsigned int"},
	{"SHRT_MIN", 	SHRT_MIN, 	"min value of short"},
	{"SHRT_MAX", 	SHRT_MAX, 	"max value of short"},
	{"USHRT_MAX", 	USHRT_MAX, 	"max value of unsigned short"},
	{"LONG_MAX", 	LONG_MAX, 	"max value of long"},
	{"LONG_MIN", 	LONG_MIN, 	"min value of long"},
	{"ULONG_MAX", 	ULONG_MAX, 	"max value of unsigned long"},
	{"LLONG_MAX", 	LLONG_MAX, 	"max value of long long"},
	{"LLONG_MIN", 	LLONG_MIN, 	"min value of long long"},
	{"ULLONG_MAX", 	ULLONG_MAX, "max value of unsigned long long"},
	{"MB_LEN_MAX", 	MB_LEN_MAX, "max number of bytes in a multibyte character constant"},

#ifdef FOPEN_MAX
	{"FOPEN_MAX",	FOPEN_MAX, 	"minimum number of standard I/O streams"},
#else
	{"FOPEN_MAX",	0,			"minimum number of standard I/O streams (not defined)"},
#endif

#ifdef STREAM_MAX
	{"STREAM_MAX", STREAM_MAX, 	"same as the FOPEN_MAX defined by POSIX.1"},
#else
	{"STREAM_MAX", 0,			"same as the FOPEN_MAX defined by POSIX.1 (not defined)"},
#endif

#ifdef TMP_MAX
	{"TMP_MAX",		TMP_MAX,	"maximum number of unique filenames generated by the 'tmpnam' function"},
#else
	{"TMP_MAX",		0,			"maximum number of unique filenames generated by the 'tmpnam' function (not defined)"},
#endif

#ifdef FILENAME_MAX
	{"FILENAME_MAX", FILENAME_MAX, "avoid using it"},
#else
	{"FILENAME_MAX", 0,			   "avoid using it (not defined)"},
#endif
};

// POSIX.1 invariant minimum values
limit_t lim_posix1[] = {
	{"_POSIX_ARG_MAX",	 	_POSIX_ARG_MAX, 	"length of arguments to 'exec' functions"},
	{"_POSIX_CHILD_MAX", 	_POSIX_CHILD_MAX,	"number of child processes per real user ID"},
	{"_POSIX_HOST_NAME_MAX",_POSIX_HOST_NAME_MAX,"maximum length of a host name as returned by 'gethostname'"},
	{"_POSIX_LINK_MAX",		_POSIX_LINK_MAX,	"number of links to a file"},
	{"_POSIX_LOGIN_NAME_MAX", _POSIX_LOGIN_NAME_MAX, "maximum length of a login name"},
	{"_POSIX_MAX_CANON", 	_POSIX_MAX_CANON,	"number of bytes on a terminal's canonical input queue"},
	{"_POSIX_MAX_INPUT",	_POSIX_MAX_INPUT,	"space available on a terminal's input queue"},
	{"_POSIX_NAME_MAX",		_POSIX_NAME_MAX,	"number of bytes in a filename, not including the terminating null"},
	{"_POSIX_NGROUPS_MAX",	_POSIX_NGROUPS_MAX,	"number of simultaneous supplementary group IDs per process"},
	{"_POSIX_OPEN_MAX",		_POSIX_OPEN_MAX,	"number of open files per process"},
	{"_POSIX_PATH_MAX",		_POSIX_PATH_MAX,	"number of bytes in a pathname, including the terminating null"},
	{"_POSIX_PIPE_BUF",		_POSIX_PIPE_BUF,	"number of bytes that can be written atomically to a pipe"},	
	{"_POSIX_RE_DUP_MAX",	_POSIX_RE_DUP_MAX,	"number of repeated occurrences of a basic regular expression permitted by the 'regexec' and 'regcomp' functions when using the interval notation \{m,n\}"},
	{"_POSIX_SSIZE_MAX",	_POSIX_SSIZE_MAX,	"value that can be stored in ssize_t object"},
	{"_POSIX_STREAM_MAX",	_POSIX_STREAM_MAX,	"number of standard I/O streams a process can have open at once"},
	{"_POSIX_SYMLINK_MAX",	_POSIX_SYMLINK_MAX,	"number of bytes in a symbolic link"},
	{"_POSIX_SYMLOOP_MAX",	_POSIX_SYMLOOP_MAX,	"number of symbolic links that can be traversed during pathname resolution"},
	{"_POSIX_TTY_NAME_MAX",	_POSIX_TTY_NAME_MAX,"length of a terminal device name, including the terminating null"},
	{"_POSIX_TTY_NAME_MAX",	_POSIX_TTY_NAME_MAX,"number of bytes for the name of a time zone"},
	{"_POSIX_SAVED_IDS",	_POSIX_SAVED_IDS,	"support saved ID"},
};

// XSI invariant minimum values
limit_t lim_xsi[] = {
#ifdef	NL_ARGMAX 
	{"NL_ARGMAX", 			NL_ARGMAX,			"maximum value of digit in calls to 'printf' and 'scanf'"},
#else
	{"NL_ARGMAX", 			0,					"maximum value of digit in calls to 'printf' and 'scanf' (not defined)"},
#endif

#ifdef	NL_LANGMAX
	{"NL_LANGMAX",			NL_LANGMAX,			"maximum number of bytes in LANG environment variable"},
#else
	{"NL_LANGMAX",			0,					"maximum number of bytes in LANG environment variable (not defined)"},
#endif

#ifdef	NL_MSGMAX
	{"NL_MSGMAX",			NL_MSGMAX,			"maximm message number"},
#else
	{"NL_MSGMAX",			0,					"maximm message number (not defined)"},
#endif

#ifdef	NL_NMAX
	{"NL_NMAX",				NL_NMAX,			"maximum number of bytes in N-to-1 mapping characters"},
#else
	{"NL_NMAX",				0,					"maximum number of bytes in N-to-1 mapping characters (not defined)"},
#endif

#ifdef	NL_SETMAX
	{"NL_SETMAX",			NL_SETMAX,			"maximum set number"},
#else
	{"NL_SETMAX",			0,					"maximum set number (not defined)"},
#endif

#ifdef	NL_TEXTMAX
	{"NL_TEXTMAX",			NL_TEXTMAX,			"maximum number of bytes in a message string"},
#else
	{"NL_TEXTMAX",			0,					"maximum number of bytes in a message string (not defined)"},
#endif

#ifdef	NZERO
	{"NZERO",				NZERO,				"default process priority"},
#else
	{"NZERO",				0,					"default process priority (not defined)"},
#endif

#ifdef	_XOPEN_IOV_MAX
	{"_XOPEN_IOV_MAX",		_XOPEN_IOV_MAX,		"maximum number of 'iovec' structures that can be used with 'readv' or 'writev'"},
#else
	{"_XOPEN_IOV_MAX",		0,					"maximum number of 'iovec' structures that can be used with 'readv' or 'writev' (not defined)"},
#endif

#ifdef	_XOPEN_NAME_MAX
	{"_XOPEN_NAME_MAX",		_XOPEN_NAME_MAX,	"number of bytes in a filename"},
#else
	{"_XOPEN_NAME_MAX",		0,					"number of bytes in a filename (not defined)"},
#endif

#ifdef	_XOPEN_PATH_MAX
	{"_XOPEN_PATH_MAX",		_XOPEN_PATH_MAX,	"number of bytes in a pathname"},	
#else
	{"_XOPEN_PATH_MAX",		0,					"number of bytes in a pathname (not defined)"},	
#endif
};

// Limits and name arguments to 'sysconf'
limit_t lim_sys[] = {
//ARG_MAX
#ifdef ARG_MAX
	{"ARG_MAX",				ARG_MAX,		""},
#else
	{"ARG_MAX",				-1,				"no symbol"},
#endif
	{"SC ARG_MAX",				_SC_ARG_MAX,			"maximum length, in bytes of arguments to the 'exec' functions"},

//ATEXIT_MAX
#ifdef ATEXIT_MAX
	{"ATEXIT_MAX",				ARG_MAX,		""},
#else
	{"ATEXIT_MAX",				-1,				"no symbol"},
#endif
	{"SC ATEXIT_MAX",			_SC_ATEXIT_MAX,			"maximum number of functions that can be registered with the 'atexit' function"},

//CHILD_MAX
#ifdef CHILD_MAX
	{"CHILD_MAX",				CHILD_MAX,		""},
#else
	{"CHILD_MAX",				-1,				"no symbol"},
#endif
	{"SC CHILD_MAX",			_SC_CHILD_MAX,			"maximum number of processes per real user ID"},

// clock ticks/second
	{"SC clock ticks/second",	_SC_CLK_TCK,			"number of clock ticks per second"},

// COLL_WEIGHT_MAX
#ifdef COLL_WEIGHTS_MAX
	{"COLL_WEIGHTS_MAX",	COLL_WEIGHTS_MAX,	""},
#else
	{"COLL_WEIGHTS_MAX",	-1,					"no symbol"},
#endif
	{"SC COLL_WEIGHTS_MAX",	_SC_COLL_WEIGHTS_MAX,	"maximum number of weights that can be assigned to an entry of the LC_COLLATE order keyword in the locale definition file"},

//HOST_NAME_MAX
#ifdef HOST_NAME_MAX
	{"HOST_NAME_MAX",		HOST_NAME_MAX,		""},
#else
	{"HOST_NAME_MAX",		-1,					"no symbol"},
#endif
	{"SC HOST_NAME_MAX",	_SC_HOST_NAME_MAX,		"maximum length of a host name as returned by 'gethostname'"},

//IOV_MAX
#ifdef IOV_MAX
	{"IOV_MAX",				IOV_MAX,			""},
#else
	{"IOV_MAX",				-1,			"no symbol"},
#endif
	{"SC IOV_MAX",				_SC_IOV_MAX,			"maximum number of 'iovec' structures that can be used with 'readv' or 'writev'"},

//LINE_MAX
#ifdef	LINE_MAX
	{"LINE_MAX",			LINE_MAX,			""},
#else
	{"LINE_MAX",			-1,			"no symbol"},
#endif
	{"SC LINE_MAX",			_SC_LINE_MAX,			"maximum length of a utility's input line"},

//LOGIN_NAME_MAX
	{"SC LOGIN_NAME_MAX",		_SC_LOGIN_NAME_MAX,		"maximum length of a login name"},
	{"SC NGROUPS_MAX",			_SC_NGROUPS_MAX,		"maximum number of simultaneous supplementary process group IDs per process"},
	{"SC OPEN_MAX",			_SC_OPEN_MAX,			"maximum number of open files per process"},
	{"SC PAGESIZE",			_SC_PAGESIZE,			"system memory page size, in bytes"},
	{"SC PAGE_SIZE",			_SC_PAGE_SIZE,			"system memory page size, in bytes"},
	{"SC RE_DUP_MAX",			_SC_RE_DUP_MAX,			"number of repeated occurrences of a basic regular expression permitted by the 'regexec' and 'regcomp' functions when using the interval notation \{m,n\}"},
	{"SC STREAM_MAX",			_SC_STREAM_MAX,			"maximum number of standard I/O streams per process at any given time; if defined, it must have the same value as FOPEN_MAX"},
	{"SC SYMLOOP_MAX",			_SC_SYMLOOP_MAX,		"number of symbolic links that can be traversed during pathname resolution"},
	{"SC TTY_NAME_MAX",		_SC_TTY_NAME_MAX,		"length of a terminal device name, including the terminating null"},
	{"SC TZNAME_MAX",			_SC_TZNAME_MAX,			"maximum number of bytes for the name of a time zone"},

#ifdef _SC_SAVED_IDS
	{"SC SAVED_IDS",		_SC_SAVED_IDS,		"saved ID supportted"},
#else
	{"SC SAVED_IDS",		-1,		""},
#endif
};

void print(limit_t *lim); 
void print_sys(limit_t *lim);
void print_lim(limit_t *lim, int num, char *name, int mode);
void print_all();

int main(int argc, char **argv) {
	print_all();
	printf("POSIX Version: %ld\n", _POSIX_VERSION);
	return 0;
}

void print_lim(limit_t *lim, int num, char *name, int mode) {
	int i;
	
	if (name == NULL) {
		for (i = 0; i < num; i++) {
			switch (mode) {
				case LIMIT_RUNTIME_SYS:
					print_sys(&lim[i]);
					break;
				case LIMIT_RUNTIME_PATH:
					break;
				case LIMIT_COMPILE_TIME:
				default:
					print(&lim[i]);
					break;
			}
		}
	} else {
		for (i = 0; i < num; i++) {
			if (!strcmp(lim[i].name, name)) {
				switch (mode) {
					case LIMIT_RUNTIME_SYS:
						print_sys(&lim[i]);
						break;
					case LIMIT_RUNTIME_PATH:
						break;
					case LIMIT_COMPILE_TIME:
					default:
						print(&lim[i]);
						break;
				}
			}
		}
	}
}

void print_all() {
	printf("ISO C:\n");
	print_lim(lim_isoc, sizeof(lim_isoc) / sizeof(limit_t), NULL, LIMIT_COMPILE_TIME);
	printf("POSIX.1:\n");
	print_lim(lim_posix1, sizeof(lim_posix1) / sizeof(limit_t), NULL, LIMIT_COMPILE_TIME);
	printf("XSI:\n");
	print_lim(lim_xsi, sizeof(lim_xsi) / sizeof(limit_t), NULL, LIMIT_COMPILE_TIME);
	printf("SYSCONF:\n");
	print_lim(lim_sys, sizeof(lim_sys) / sizeof(limit_t), NULL, LIMIT_RUNTIME_SYS);
}

void print(limit_t *lim) {
	if (!strncmp(lim->name, "U", 1))
		printf("%22s    %20llu    %s\n", lim->name, lim->value, lim->desc);
	else
		printf("%22s    %20lld    %s\n", lim->name, lim->value, lim->desc);
}

void print_sys(limit_t *lim) {
	long value = sysconf(lim->value);
	char *errstr = NULL;

	if (!strncmp(lim->name, "SC", 2)) {
		value = sysconf(lim->value);

		if (value < 0) {
			if (errno != 0) {
				if (errno == EINVAL)
					errstr = "not supported";
				else
					errstr = "sysconf error";
			} else {
				errstr = "no limit";
			}
		} 
		printf("%22s    %20ld    %s", lim->name, value, lim->desc);

		if (errstr != NULL)
			printf(" (%s)\n", errstr);
		else
			printf("\n");
	} else {
		printf("%22s    %20ld    %s\n", lim->name, value, lim->desc);
	}
}
